/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuthenticationResponse } from '../model/models';
import { UpdateTransmission400Response } from '../model/models';
import { User } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateCustomerRequestParams {
    authenticationResponse: AuthenticationResponse;
}

export interface DeleteUSerRequestParams {
    userId: number;
}

export interface GetUSerByIDRequestParams {
    userId: number;
}

export interface LoginRequestParams {
    authenticationResponse: AuthenticationResponse;
}

export interface RefreshTokenRequestParams {
    authenticationResponse: AuthenticationResponse;
}

export interface UpdateUserRequestParams {
    userId: number;
    user: User;
}


export interface AuthenticationControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    createCustomer(requestParameters: CreateCustomerRequestParams, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
* @param requestParameters
     */
    deleteUSer(requestParameters: DeleteUSerRequestParams, extraHttpRequestParams?: any): Observable<AuthenticationResponse>;

    /**
     * 
     * 
*/
    getAllUsers(extraHttpRequestParams?: any): Observable<AuthenticationResponse>;

    /**
     * 
     * 
*/
    getMyProfile(extraHttpRequestParams?: any): Observable<AuthenticationResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    getUSerByID(requestParameters: GetUSerByIDRequestParams, extraHttpRequestParams?: any): Observable<AuthenticationResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    login(requestParameters: LoginRequestParams, extraHttpRequestParams?: any): Observable<AuthenticationResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    refreshToken(requestParameters: RefreshTokenRequestParams, extraHttpRequestParams?: any): Observable<AuthenticationResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateUser(requestParameters: UpdateUserRequestParams, extraHttpRequestParams?: any): Observable<AuthenticationResponse>;

}
