/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Car } from '../model/models';
import { CarDto } from '../model/models';
import { CreateCarRequest } from '../model/models';
import { UpdateCarRequest } from '../model/models';
import { UpdateTransmission400Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AddCarRequestParams {
    createCarRequest: CreateCarRequest;
}

export interface DeleteCarRequestParams {
    id: number;
}

export interface GetCarByIdRequestParams {
    id: number;
}

export interface GetCarsByModelNameRequestParams {
    modelName: string;
}

export interface UpdateCarRequestParams {
    updateCarRequest: UpdateCarRequest;
}


export interface CarsControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    addCar(requestParameters: AddCarRequestParams, extraHttpRequestParams?: any): Observable<CarDto>;

    /**
     * 
     * 
* @param requestParameters
     */
    deleteCar(requestParameters: DeleteCarRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    getAllCar(extraHttpRequestParams?: any): Observable<Array<CarDto>>;

    /**
     * 
     * 
* @param requestParameters
     */
    getCarById(requestParameters: GetCarByIdRequestParams, extraHttpRequestParams?: any): Observable<CarDto>;

    /**
     * 
     * 
* @param requestParameters
     */
    getCarsByModelName(requestParameters: GetCarsByModelNameRequestParams, extraHttpRequestParams?: any): Observable<Array<Car>>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateCar(requestParameters: UpdateCarRequestParams, extraHttpRequestParams?: any): Observable<CarDto>;

}
