/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Model } from './model';
import { CarDto } from './car-dto';


export interface Car { 
    id?: number;
    createdDate?: string;
    updatedDate?: string;
    deletedDate?: string;
    modelYear?: number;
    plate?: string;
    state?: number;
    dailyPrice?: number;
    model?: Model;
    dto?: CarDto;
}

